server:
  port: 12000
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/derozan-su/study-springCloud.git
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
